/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.unisiga.view;

import org.unisiga.controller.InscripcionController;
import org.unisiga.view.VentanaInscripcion;
/**
 *
 * @author andy
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private InscripcionController controller;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(InscripcionController controller) {
        this.controller = controller;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        modulos = new javax.swing.JMenu();
        reportesConsultas = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        sistema = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        modulos.setText("Modulos");

        reportesConsultas.setText("Inscripcion de Asignaturas");
        reportesConsultas.addActionListener(this::reportesConsultasActionPerformed);
        modulos.add(reportesConsultas);

        menuReportes.setText("Registro Notas");
        menuReportes.addActionListener(this::menuReportesActionPerformed);
        modulos.add(menuReportes);

        jMenuItem3.setText("Reportes y consultas");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        modulos.add(jMenuItem3);

        jMenuBar1.add(modulos);

        sistema.setText("Sistema");

        salir.setText("Salir");
        salir.addActionListener(this::salirActionPerformed);
        sistema.add(salir);

        jMenuBar1.add(sistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportesConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesConsultasActionPerformed
        // TODO add your handling code here:
        new VentanaInscripcion(controller).setVisible(true);
    }//GEN-LAST:event_reportesConsultasActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this,"Módulo de Reportes (pendiente de crear).");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void menuReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportesActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this,"Módulo de Registro de Notas (pendiente de crear).");
    }//GEN-LAST:event_menuReportesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem menuReportes;
    private javax.swing.JMenu modulos;
    private javax.swing.JMenuItem reportesConsultas;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenu sistema;
    // End of variables declaration//GEN-END:variables
}
